server:
  port: 8080

spring:
  profiles:
     include:
       - secret

  security:
    oauth2:
      client:
        registration:
          kakao:
            - secret
          naver:
            - secret
          google:
            - secret
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true

jwt:
    - secret

cloud:
    - secret

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.debugging.debugging: debug