server:
  port: 8080

spring:
  profiles:
     include:
       - secret

  security:
    oauth2:
      client:
        registration:
          kakao:
            - secret
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

jwt:
    - secret

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.debugging.debugging: debug